spring:
  batch:
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:postgresql://pg-test-notes-app.c05rouaiy1pi.us-east-1.rds.amazonaws.com:5432/notes
    username: postgres
    password: A1a1a1$#
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

logging:
  level:
    root: INFO

parquet:
  path: "resources/notes.parquet"

batch:
  chunk: 10
