version: '3'

services:
  notes:
    build:
      context: ./notes/application
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./init-db-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
  
