version: '3'

services:
  notes:
    build:
      context: ./notes/application
    links: 
      - db
      - users
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notes
      - USERS_HOST=users
      - USERS_PORT=9000
    ports:
      - 8080:8080

  users:
    build:
      context: ./users/application
    links: 
      - db
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/users
    ports:
      - 9000:9000

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./init-db-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data:

