spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notes
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

users:
  host: 127.0.0.1
  port: 9000
